# Generated by Django 3.1.4 on 2021-06-10 06:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Category name')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
        ),
        migrations.CreateModel(
            name='Tasks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Task title')),
                ('description', models.TextField(verbose_name='Task description')),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='Datetime')),
                ('status_task', models.CharField(max_length=50, verbose_name='Status of task')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='post.project', verbose_name='Project')),
            ],
        ),
    ]
