# Generated by Django 3.1.4 on 2021-06-10 10:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0003_project_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='date',
        ),
    ]
